### ISSUE TITLE
Make the punctuation in statuses.py consistent

### ISSUE THREAD

**Issue by achasveachas** [achasveachas/hug-bot#27]
Right now there are some statuses that have a period at the end and some that don't.

Ideally, they should all have a period at the end.

### Proposed workflow:
1. Fork the repo
1. Go through the `statuses.py` file and a dd a period to the end of each sentance that doesn't have one
1. Once you are done and checked for typos, commit it and push your work to your fork
1. Submit a PR against this repo
1. If you have a Twitter handle please let me know so I can give you a proper shout-out 🤗 

Someone will look it over and, if everything is ok, will merge your PR.

Thanks for contributing!

**Comment by rosita-dmello** [comment]
Hi, I'd like to work on this! Can you assign it to me?

**Comment by achasveachas** [comment]
No need for assignment, just submit the PR and I'll accept it :)

**Comment by achasveachas** [comment]
Fixed by #28
